Benchmarks
vla5924-practice/compiler-project pull request #105
Opened 2024-03-25 18:27 UTC by MaksimShagov

2024-03-25 18:28 UTC, MaksimShagov commented on benchmarks/flex/lexer.l
> +#include "token_types.hpp"
delete this

2024-03-25 19:29 UTC, vla5924 requested changes
Насчет изменений в cli не уверен, возможно, стоит сделать их отдельным патчем

2024-03-25 19:29 UTC, vla5924 commented on compiler/include/compiler/utils/timer.hpp
> +        using time_point = std::chrono::time_point<std::chrono::steady_clock>;
у нас используется PascalCase для типов

2024-03-25 19:29 UTC, vla5924 commented on compiler/include/compiler/utils/timer.hpp
> +            return std::chrono::duration_cast<std::chrono::milliseconds>(end_point - start_point).count();
Есть мнение что этот метод можно объединить с end, а start переименовать в reset

2024-03-25 19:29 UTC, vla5924 commented on compiler/lib/cli/compiler.cpp
> +    parser.add_argument("--dissable-log", ARG_DISABLE_LOG)
Вроде как за это отвечает опция -v

2024-03-25 19:29 UTC, vla5924 commented on benchmarks/utils/generate_files.py
> +class Keyword(Enum):
В чем разница с тем, что объявлено в run_benchmark?

2024-03-25 19:29 UTC, vla5924 commented on benchmarks/flex/build.sh
> +flex  lexer.l
Вообще, вместо build.sh можно сделать такой же короткий Makefile

2024-03-25 19:29 UTC, vla5924 commented on benchmarks/utils/generate_files.py
> +    words = list(operators.keys()) + list(keywords.keys())
А list зачем?

2024-03-25 19:29 UTC, vla5924 commented on benchmarks/run_bechmark.py
Я бы этот файл в runner.py переименовал, он же и так в папке benchmarks лежит

2024-03-26 16:44 UTC, MaksimShagov commented on benchmarks/utils/generate_files.py
> +    words = list(operators.keys()) + list(keywords.keys())
keys() и values() - объекты типа dict_keys и dict_values. их нельзя объединять просто так, но можно итерироваться по ним в цикла. Можно их воспринимать, как +-генераторы.

2024-03-26 17:02 UTC, vla5924 commented on benchmarks/utils/generate_files.py
> +    words = list(operators.keys()) + list(keywords.keys())
Ок, тогда предлагаю `[*operators.keys(), *keywords.keys()]`

2024-04-03 17:54 UTC, MaksimShagov commented on benchmarks/runner.py
> +        tokenize_times.append(times)
Надо засунуть в функцию

2024-04-07 08:57 UTC, MaksimShagov commented on compiler/lib/cli/compiler.cpp
> +const char *const ARG_TIMES = "--times";
@vla5924, вроде clang-tidy по делу орет, но только на новые ченжи)

2024-04-07 10:45 UTC, vla5924 commented on compiler/lib/cli/compiler.cpp
> +const char *const ARG_TIMES = "--times";
так он все правильно орет, это мы будем переименовывать в camelCase

2024-04-07 14:53 UTC, vla5924 submitted a review, later dismissed

2024-04-08 16:02 UTC, vla5924 approved these changes

2024-04-10 05:03 UTC, arteboss approved these changes

2024-04-10 05:03 UTC, merged