List support in lexer and parser
vla5924-practice/compiler-project pull request #127
Opened 2024-04-29 10:04 UTC by MaksimShagov

2024-04-29 11:03 UTC, MaksimShagov commented
@vla5924 предварительно посмотри, какие деревья получаются. Скажи что можно поправить

2024-04-30 09:52 UTC, arteboss commented on compiler/lib/frontend/parser/parser.cpp
> +            ast::Node::Ptr callNode = std::get<ast::Node::Ptr>(subexpr);
Может добавить using ast::Node:Ptr чтоб не карячить везде эту конструкцию?

2024-05-01 09:07 UTC, vla5924 commented on compiler/lib/frontend/parser/parser.cpp
> +            ast::Node::Ptr callNode = std::get<ast::Node::Ptr>(subexpr);
там вообще using namespace ast написано

2024-05-01 09:14 UTC, vla5924 commented on compiler/tests/frontend/parser.cpp
> +        "    x : int = mylist[0]",
1. предлагаю добавить еще тест с более сложным выражением, например: `1 + mylist[0] - (mylist[1] * 2 * mylist[2])`
2. поддерживается ли переменная, вызов функции или другое произвольное выражение в качестве индекса?

2024-05-01 09:15 UTC, vla5924 requested changes

2024-05-01 09:15 UTC, vla5924 commented on compiler/tests/frontend/parser.cpp
> +TEST(Parser, can_parse_list) {
```suggestion
TEST(Parser, can_parse_list_declaration) {
```

2024-05-01 09:15 UTC, vla5924 commented on compiler/tests/frontend/parser.cpp
> +TEST(Parser, can_parse_list_defenition) {
```suggestion
TEST(Parser, can_parse_list_definition) {
```

2024-05-01 09:41 UTC, arteboss commented on compiler/tests/frontend/parser.cpp
> +TEST(Parser, can_parse_list_defenition) {
Хахаха

2024-05-02 16:51 UTC, vla5924 requested changes

2024-05-02 16:51 UTC, vla5924 commented on compiler/include/compiler/frontend/lexer/token_types.hpp
> +    List
```suggestion
    List,
```

2024-05-02 16:51 UTC, vla5924 commented on compiler/lib/frontend/parser/parser.cpp
> +#include "compiler/ast/node.hpp"
верни на место, зачем подвинул

2024-05-02 16:51 UTC, vla5924 commented on compiler/lib/frontend/parser/parser.cpp
> +namespace parser {
лучше все экс-static функции в этом файле тоже поместить в анонимный неймспейс (объединить с тем что выше)

2024-05-02 16:51 UTC, vla5924 commented on compiler/lib/frontend/parser/parser.cpp
> +} // namespace parser
```suggestion

} // namespace

```

2024-05-02 17:12 UTC, MaksimShagov commented on compiler/lib/frontend/parser/parser.cpp
> +using SubExpression = std::variant<TokenIterator, Node::Ptr>;
![image](https://github.com/vla5924-practice/compiler-project/assets/43129418/8bfd8ac0-ee1e-42f4-8d06-714736028d11)

2024-05-02 17:22 UTC, MaksimShagov commented on compiler/lib/frontend/parser/parser.cpp
> +    Node::Ptr currNode = root;
а че ты на первый аргумент не ругаешься

2024-05-02 19:09 UTC, vla5924 commented on compiler/lib/frontend/parser/parser.cpp
> +    Node::Ptr currNode = root;
потому что он не only copied once, у него вызываются не const методы

2024-05-02 19:12 UTC, vla5924 commented on compiler/lib/frontend/parser/parser.cpp
> +    Node::Ptr currNode = root;
и да, все-таки здесь должно быть `const Node::Ptr &root`

2024-05-02 19:15 UTC, vla5924 requested changes
с пивом пойдет

2024-05-03 03:48 UTC, MaksimShagov commented on compiler/lib/frontend/parser/parser.cpp
> +void buildExpressionSubtree(std::stack<SubExpression> &postfixForm, Node::Ptr &root, ErrorBuffer &errors) {
Тесты не упали и на том спасибо

2024-05-03 14:27 UTC, vla5924 approved these changes
нажми Update branch, Enable auto-merge

2024-05-04 07:46 UTC, arteboss approved these changes

2024-05-04 07:47 UTC, merged