Fold constants
vla5924-practice/compiler-project pull request #128
Opened 2024-04-29 14:52 UTC by arteboss

2024-04-29 15:06 UTC, arteboss commented on compiler/lib/backend/optree/optimizer/opt_builder.cpp
> +#include <algorithm>
понял

2024-04-29 15:06 UTC, arteboss commented on compiler/lib/backend/optree/optimizer/transforms/fold_constants.cpp
> +    static void foldLogicUnaryOp(const LogicUnaryOp &op, OptBuilder &builder) {
точняк, забыл, спасибо

2024-04-30 09:48 UTC, arteboss commented on compiler/lib/backend/optree/optimizer/transforms/fold_constants.cpp
> +        }
```suggestion
        }
        auto newOp = builder.insert<ConstantOp>(op->ref, type, folded);
        builder.replace(op, newOp);
        return;
```

2024-05-01 17:44 UTC, vla5924 requested changes
после того как #129 #130 будут запушены нужно добавить для FoldConstants аналогичные тесты

2024-05-10 17:43 UTC, arteboss commented
все сделал пацаны

2024-05-10 17:45 UTC, arteboss commented
все сделал мужики

2024-05-10 17:52 UTC, arteboss commented on compiler/lib/backend/optree/optimizer/transforms/fold_constants.cpp
> +#include <cassert>
норм

2024-05-10 18:25 UTC, vla5924 submitted a review, later dismissed
неплохие коды

2024-05-11 11:35 UTC, vla5924 requested changes

2024-05-11 11:35 UTC, vla5924 commented on compiler/include/compiler/optree/adaptors.hpp
изменения в этом файле будут не нужны после #155

2024-05-11 11:35 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/fold_constants.cpp
> +#include "optimizer/transform.hpp"
этот инклюд должен быть в последней секции

2024-05-11 11:35 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/fold_constants.cpp
> +            int64_t folded;
вместо явного использования "конкретных" типов надо использовать NativeInt, NativeFloat, NativeBool

2024-05-11 11:35 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/fold_constants.cpp
> +            int64_t rhs = rhsOp.value().as<int64_t>();
тут можно поставить auto так как тип и так упоминается, ниже для флотов и тд тоже

2024-05-11 11:35 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/fold_constants.cpp
> +#include <cstdint>
cstdint будет не нужен после перехода на NativeInt

2024-05-13 06:34 UTC, MaksimShagov approved these changes

2024-05-13 07:16 UTC, vla5924 approved these changes

2024-05-13 07:16 UTC, merged