Support for, range, enumarate syntax in lexer and parser
vla5924-practice/compiler-project pull request #144
Opened 2024-05-05 09:30 UTC by MaksimShagov

2024-05-05 10:42 UTC, vla5924 requested changes

2024-05-05 10:42 UTC, vla5924 commented on compiler/include/compiler/ast/node_type.hpp
> +    ForStartedList,
1. значения должны быть отсортированы по алфавиту
2. предлагаю другие названия: ForTargets, ForIterable

2024-05-05 10:42 UTC, vla5924 commented on compiler/lib/frontend/lexer/lexer.cpp
> +    {"while", Keyword::While},
если просто заменить range на list и ничего не переставлять то тоже так отформатируется?

2024-05-05 10:42 UTC, vla5924 commented on compiler/lib/frontend/parser/parser.cpp
> +            ctx.pushError("Enexepted token here");
```suggestion
            ctx.pushError("Unexpected token in a for statement");
```

2024-05-05 10:42 UTC, vla5924 commented on compiler/tests/frontend/lexer.cpp
> +    StringVec source = {"for i in range(10)", "for i in enumerate(10)"};
в enumerate можно пихать только лист

2024-05-05 10:42 UTC, vla5924 commented on compiler/tests/frontend/parser.cpp
> +        "def main() -> None:", "    for i in range(0, 10, 1):",
range с одним и двумя аргументами тоже работает?

2024-05-05 10:42 UTC, vla5924 commented on compiler/tests/frontend/parser.cpp
> +        "def main() -> None:", "    for i in range(0, 10, 1):",
и еще более сложные выражения в аргументах

2024-05-05 10:42 UTC, vla5924 commented on compiler/include/compiler/frontend/lexer/token.hpp
> +    bool is(const TokenType &value) const {
вообще мы тип явно поле type сравнивали, но ладно

2024-05-05 10:51 UTC, vla5924 commented on compiler/tests/frontend/parser.cpp
> +        "def main() -> None:", "    for i in range(0, 10, 1):",
по идее for value in list тоже должно работать

2024-05-05 13:50 UTC, MaksimShagov commented on compiler/lib/frontend/lexer/lexer.cpp
> +    {"while", Keyword::While},
Да

2024-05-06 15:37 UTC, vla5924 commented on compiler/include/compiler/ast/node_type.hpp
> +} // namespace ast
молодец, а теперь верни перенос строки

2024-05-06 15:37 UTC, vla5924 commented on compiler/lib/frontend/lexer/lexer.cpp
> +    {"while", Keyword::While},
мда, такой дифф плохо выглядит, тогда надо откатывать и оборачивать список в // clang-format off и on

2024-05-06 15:39 UTC, vla5924 commented on compiler/lib/frontend/lexer/lexer.cpp
> +    {"while", Keyword::While},
мда, такой дифф плохо выглядит, тогда надо откатывать и оборачивать список в // clang-format off и on

2024-05-06 15:59 UTC, vla5924 commented on compiler/lib/frontend/lexer/lexer.cpp
> +    {"while", Keyword::While},
ну или можно забить

2024-05-10 06:47 UTC, vla5924 approved these changes

2024-05-10 16:47 UTC, arteboss approved these changes

2024-05-10 16:47 UTC, merged