Implement optree transformation: Erase unused functions
vla5924-practice/compiler-project pull request #146
Opened 2024-05-10 08:48 UTC by MaksimShagov

2024-05-10 09:00 UTC, MaksimShagov commented on compiler/lib/optree/operation.cpp
> +    }
@vla5924. при удалении узла у которого больше одного ребенка, все циклы на ренжах делают бочку и инвалидируются. Как предложение, переделать erase на clear, который чистит все нижележащие от оператора на котором был вызван метод, а саму операцию удалять после вызова clear где-то наверху, либо метод, типа eraseChild и звать всегда его от родителя.

2024-05-10 14:01 UTC, vla5924 requested changes

2024-05-10 18:21 UTC, vla5924 requested changes

2024-05-10 18:21 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/erase_unused_functions.cpp
> +    using CallEdges = std::multimap<std::string, std::string>;
если сделать `map<string, list<string>` то будет проще реализация, вместо deque от `edges.equal_range("main")` можно будет писать `edges["main"]` и тд

2024-05-10 18:21 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/erase_unused_functions.cpp
> +        for (auto it : utils::advanceEarly(op->body.begin(), op->body.end())) {
это не `auto it`, это `const auto &op`

2024-05-10 18:21 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/erase_unused_functions.cpp
> +#include <unordered_set>
сначала должны быть инклюды из стандартной библиотеки, потом из compiler/..., потом из своей папки (optimizer/opt_builder.hpp), и еще между секциями пустые строки
```suggestion
#include <deque>
#include <map>
#include <memory>
#include <string>
#include <unordered_set>

#include "compiler/optree/adaptors.hpp"
#include "compiler/optree/operation.hpp"

#include "optimizer/opt_builder.hpp"
#include "optimizer/transform.hpp"
```

2024-05-10 18:21 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/erase_unused_functions.cpp
> +            if (!usedFunctions.contains(queue.front().second)) {
`queue.front().second` можно сохранить в переменную и использовать

2024-05-10 18:35 UTC, vla5924 requested changes

2024-05-10 18:35 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/erase_unused_functions.cpp
> +    using CallEdges = std::map<std::string, std::list<std::string>>;
тут ваще unordered_set вместо list можно использовать я думаю

2024-05-10 18:35 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/erase_unused_functions.cpp
> +        auto mainFunctions = edges["main"];
эх, ссылку бы

2024-05-10 18:35 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/erase_unused_functions.cpp
> +        std::deque<std::string> queue(mainFunctions.begin(), mainFunctions.end());
почему бы сразу этот mainFunctions не использовать?

2024-05-10 18:35 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/erase_unused_functions.cpp
> +                auto innerFunctions = edges[name];
эх, ссылку бы (2)

2024-05-11 06:39 UTC, MaksimShagov commented on compiler/lib/backend/optree/optimizer/transforms/erase_unused_functions.cpp
> +        std::deque<std::string> queue(mainFunctions.begin(), mainFunctions.end());
usedFunctions - сет вершин, которые можно посетить из мейна. 
mainFunctions - сет ближайших вершин, которые можно посетить из мейна(первые потомки от мейна).
Фактически происходит поиск в ширину для графа с возможными циклами. usedFunctions по своей сути агрегатор всех вершин и он же помогает учитывать рекурсию.

2024-05-11 11:43 UTC, vla5924 requested changes

2024-05-11 11:43 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/erase_unused_functions.cpp
> +        std::unordered_set<std::string> usedFunctions = {"main"};
после #154 тут стоит использовать language::funcMain

2024-05-11 11:43 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/erase_unused_functions.cpp
> +        for (const auto &op : utils::advanceEarly(op->body.begin(), op->body.end())) {
после #155 тут можно будет использовать `utils::advanceEarly(op->body)`

2024-05-11 11:43 UTC, vla5924 commented on compiler/tests/backend/optree/optimizer/erase_unused_functions.cpp
> +        v[0] = m.opInit<ConstantOp>(m.tI64, int64_t(123));
после #155 явный каст к int64_t и double для ConstantOp не нужен

2024-05-11 11:43 UTC, vla5924 commented on compiler/tests/backend/optree/optimizer/erase_unused_functions.cpp
> +        v[1] = m.opInit<FunctionCallOp>("test3", m.tNone, std::vector<Value::Ptr>());
`{}` вместо вектора не работает?

2024-05-11 11:43 UTC, vla5924 commented on compiler/tests/backend/optree/optimizer/erase_unused_functions.cpp
> +#include <utility>
а зачем тут утилити?

2024-05-11 12:24 UTC, MaksimShagov commented on compiler/tests/backend/optree/optimizer/erase_unused_functions.cpp
> +        v[1] = m.opInit<FunctionCallOp>("test3", m.tNone, std::vector<Value::Ptr>());
не работал

2024-05-14 15:13 UTC, vla5924 approved these changes

2024-05-15 13:27 UTC, arteboss approved these changes
Молодец

2024-05-15 13:27 UTC, merged