Implement optree transformation: Join identical conditional branches
vla5924-practice/compiler-project pull request #176
Opened 2024-05-20 18:39 UTC by MaksimShagov

2024-05-20 18:41 UTC, MaksimShagov commented on compiler/lib/backend/optree/optimizer/transforms/join_conditions_branches.cpp
> +            if (elseOp->body.size() == thenOp->body.size()) {
Вроде бы можно просто функцию сверху заколить через ренж

2024-05-25 07:43 UTC, vla5924 requested changes

2024-05-25 07:43 UTC, vla5924 commented on compiler/lib/backend/optree/optimizer/transforms/join_conditions_branches.cpp
> +        auto valueEqual = [](const Value::Ptr &lhs, const Value::Ptr &rhs) { return lhs->type == rhs->type; };
Это неправильное сравнение. Например, два таких body по твоей логике будут одинаковые, хотя value 0 и 1 используются по разному:

```txt
Op1 (...) -> (#0: float)
Op2 (...) -> (#1: float)
Op3 (#0, #1) -> (...)
---
Op1 (...) -> (#0: float)
Op2 (...) -> (#1: float)
Op3 (#1, #0) -> (...)
```

И более простой случай (если 0 и 1 созданы где-то снаружи):

```txt
Op1 (#0: float, #1: float) -> (...)
---
Op1 (#1: float, #0: float) -> (...)
```

А еще у операций есть specId и name, которые тоже должны совпадать. Надо бы вынести все это в отдельную функцию в helpers, по идее #179

2025-03-29 08:36 UTC, vla5924 approved these changes
хз

2025-03-29 08:36 UTC, merged