Parser testing
vla5924-practice/compiler-project pull request #19
Opened 2021-11-14 14:10 UTC by arteboss

2022-03-31 14:47 UTC, MaksimShagov approved these changes

2022-03-31 15:18 UTC, vla5924 requested changes

2022-03-31 15:18 UTC, vla5924 commented on tests/CMakeLists.txt
> +add_subdirectory(ast)
Тесты для ast нужно внести отдельным PR, это изменение здесь не должно быть

2022-03-31 15:18 UTC, vla5924 commented on tests/ast/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.19)
Тесты для ast нужно внести отдельным PR, этого файла здесь не должно быть

2022-03-31 15:18 UTC, vla5924 commented on tests/ast/main.cpp
> +#include <gtest/gtest.h>
Тесты для ast нужно внести отдельным PR, этого файла здесь не должно быть

2022-03-31 15:18 UTC, vla5924 commented on tests/ast/syntax_tree.cpp
> +#include <gtest/gtest.h>
Тесты для ast нужно внести отдельным PR, этого файла здесь не должно быть

2022-03-31 15:18 UTC, vla5924 commented on tests/backend/parser.cpp
> +TEST(Parser, can_parse_function_call) {
Еще надо тест на вызов функции с параметрами внутри выражения. И на объявление функции с параметрами тоже

2022-03-31 15:18 UTC, vla5924 commented on tests/backend/parser.cpp
> +        "    return 1",
Еще бы тест с более сложным выражением

2022-03-31 15:18 UTC, vla5924 commented on tests/backend/parser.cpp
> +}
Нет пустой строки

2022-04-04 14:40 UTC, arteboss commented on tests/backend/parser.cpp
> +}
есть

2022-04-04 14:41 UTC, arteboss commented on tests/backend/parser.cpp
> +        "    return 1",
сделал

2022-04-04 14:41 UTC, arteboss commented on tests/backend/parser.cpp
> +TEST(Parser, can_parse_function_call) {
готово

2022-04-04 14:48 UTC, MaksimShagov approved these changes

2022-04-04 14:48 UTC, merged