Serialization features added to console application
vla5924-practice/compiler-project pull request #21
Opened 2021-11-23 12:45 UTC by vla5924

2021-12-05 18:31 UTC, MaksimShagov requested changes

2021-12-05 18:31 UTC, MaksimShagov commented on ast/src/node.cpp
> +    // stream << "0x" << this << " ";
Этот комментарий необходим?

2021-12-05 18:33 UTC, vla5924 commented on ast/src/node.cpp
> +    // stream << "0x" << this << " ";
Так и быть, удалю

2021-12-05 18:34 UTC, vla5924 commented on ast/src/node.cpp
> +    // stream << "0x" << this << " ";
Хотя нет, давайте оставим

2021-12-05 18:37 UTC, MaksimShagov approved these changes

2021-12-07 09:32 UTC, arteboss approved these changes
красава думпинг

2021-12-07 09:32 UTC, merged