Basic semantizer implementation
vla5924-practice/compiler-project pull request #23
Opened 2021-11-28 13:51 UTC by MaksimShagov

2021-12-08 14:33 UTC, vla5924 requested changes
Продолжение следует...

2021-12-08 14:33 UTC, vla5924 commented on backend/include/backend/semantizer/semantizer.hpp
> +    static void pushTypeConversion(ast::Node::Ptr &, ast::TypeId);
Это все, как я понимаю, должно быть приватное

2021-12-08 14:33 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +std::vector<TypeId> Semantizer::getFunctionArguments(std::list<ast::Node::Ptr> &children) {
Зачем `ast::`, если есть `using namespace ast;`?
Здесь и ниже тоже.

2021-12-08 14:33 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +    for (auto &node : children) {
const auto&

2021-12-08 14:33 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +void Semantizer::parseExpression(ast::Node::Ptr &node, TypeId var_type, ast::Node::Ptr &branch) {
Не совсем подходящее название, судя по тому, что эта функция делает. Лучше что-то типа `processExpression` или `visitExpression`

2021-12-08 14:33 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +    Node::Ptr conv_node = std::make_shared<Node>(Node(NodeType::TypeConversion, node->parent));
```suggestion
    Node::Ptr conv_node = std::make_shared<Node>(NodeType::TypeConversion, node->parent);
```

2021-12-08 14:33 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +    Node::Ptr conv_node = std::make_shared<Node>(Node(NodeType::TypeConversion, node->parent));
Здесь и ниже тоже

2021-12-08 14:33 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +void Semantizer::parseBranchRoot(ast::Node::Ptr &node, ast::FunctionsTable &functions) {
Опять же лучше `processBranchRoot` или `visitBranchRoot`

2021-12-08 14:33 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +            auto type = list_it->get()->typeId();
`(*list_id)->typeId()` ?

2021-12-08 14:33 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +            auto list_it = it->children.begin();
В этом блоке `list_it` не меняется, поэтому можно сразу использовать ссылку `Node::Ptr &exprRoot = it->children.front();` или что-то в этом духе

2021-12-08 14:33 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +ast::SyntaxTree &Semantizer::process(ast::SyntaxTree &tree) {
```suggestion
void Semantizer::process(ast::SyntaxTree &tree) {
```

2021-12-08 14:33 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +}
Нет пустой строки

2021-12-08 14:33 UTC, vla5924 commented on tests/backend/semantizer.cpp
> +}
Нет пустой строки

2021-12-09 15:46 UTC, vla5924 commented
что-то про область видимости... тыры пыры...

2022-01-31 14:55 UTC, vla5924 requested changes

2022-01-31 14:55 UTC, vla5924 commented on ast/include/ast/functions_table.hpp
> +    Function(const TypeId type, const std::vector<TypeId> &args) : returnType(type), argumentsTypes(args){};
```suggestion
    explicit Function(const TypeId type, const std::vector<TypeId> &args = {}) : returnType(type), argumentsTypes(args){};
```

2022-01-31 14:55 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +#include "iostream"
Эээ?

2022-01-31 14:55 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +    for (auto &it : node->children) {
А вообще, почему `it`? Там же указатели, а не итераторы. Предлагаю `child`.

2022-01-31 14:55 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +    for (auto &it : node->children) {
Тут тоже не `it`.

2022-01-31 15:28 UTC, arteboss approved these changes
красава

2022-01-31 15:30 UTC, arteboss commented
129 строчка проверкавыхода из рекурсии

2022-01-31 15:32 UTC, vla5924 approved these changes
LGTM

2022-01-31 15:32 UTC, merged