Semantizer improvements
vla5924-practice/compiler-project pull request #24
Opened 2022-02-21 10:53 UTC by MaksimShagov

2022-03-22 16:30 UTC, vla5924 commented
Еще че-то вспомнил:
* нужно, чтобы в случае бинарных операций с `float` типы нодов заменялись на соответствующие с приставкой `F` (`FAdd`, `FSub`, etc.) (они уже есть в заголовке node_type), это нужно для IR генератора, чтобы не делать двойную работу
* насколько я понимаю, можно сделать, чтобы ноды `Expression` хранили значение `TypeId`, то есть собственно итоговый тип выражения внутри, это тоже пригодится для IR генератора
* забыл че еще пока писал

2022-03-22 16:30 UTC, vla5924 commented
Еще че-то вспомнил:
* нужно, чтобы в случае бинарных операций с `float` типы нодов заменялись на соответствующие с приставкой `F` (`FAdd`, `FSub`, etc.) (они уже есть в заголовке node_type), это нужно для IR генератора, чтобы не делать двойную работу
* насколько я понимаю, можно сделать, чтобы ноды `Expression` хранили значение `TypeId`, то есть собственно итоговый тип выражения внутри, это тоже пригодится для IR генератора
* забыл че еще пока писал

2022-04-06 13:24 UTC, vla5924 requested changes
Тут пока так, в основном чисто по оформлению

2022-04-06 13:24 UTC, vla5924 commented on ast/src/node.cpp
> +        stream << "Expression\n"; //<< typeIdToString(typeId()) << "\n";
Добавить проверку через `std::holds_alternative` и норм.

2022-04-06 13:24 UTC, vla5924 commented on backend/include/backend/semantizer/semantizer.hpp
>  #include <ast/types.hpp>
```suggestion
#include <ast/syntax_tree.hpp>
#include <ast/types.hpp>

#include "error_buffer.hpp"
#include "semantizer_error.hpp"
```

2022-04-06 13:24 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +static std::vector<TypeId> getFunctionArguments(std::list<Node::Ptr> &functionArguments) {
```suggestion
static std::vector<TypeId> getFunctionArguments(const std::list<Node::Ptr> &functionArguments) {
```

2022-04-06 13:24 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +namespace {
Эти методы наверное можно и без `namespace`, они же и так `static`

2022-04-06 13:24 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +static ast::TypeId searchVariable(const Node::Ptr &node, const std::list<VariablesTable *> &tables,
`ast::` не нужно, ниже тоже проверь

2022-04-06 13:24 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +                              FunctionsTable &functions, ErrorBuffer &errors);
Это здесь зачем? Нужно просто `processFunctionCall` подвинуть ниже

2022-04-06 13:24 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +static void parseFunctions(std::list<Node::Ptr> &children, FunctionsTable &functions, ErrorBuffer &errors) {
Тут const для children не нужен?

2022-04-06 14:09 UTC, MaksimShagov commented on backend/src/semantizer/semantizer.cpp
> +                              FunctionsTable &functions, ErrorBuffer &errors);
Они вызывают друг друга. Поэтому так.

2022-04-06 14:14 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +                              FunctionsTable &functions, ErrorBuffer &errors);
Кек, а бесконечной рекурсии в таком случае у них не может быть? и можно ли это как-то избежать?

2022-04-06 14:19 UTC, MaksimShagov commented on backend/src/semantizer/semantizer.cpp
> +                              FunctionsTable &functions, ErrorBuffer &errors);
Тут не будет бесконечной рекурсии. Т. к. каждый вызов этой функции по сути проход в глубину, а наше дерево конечное.

2022-04-06 14:39 UTC, arteboss approved these changes
полностью approve'дан

2022-04-07 16:03 UTC, vla5924 approved these changes
Пока замержим в угоду QA, а семантайзер контекст и остальные приколы отдельно надо будет доделать

2022-04-07 16:03 UTC, merged