Added tests for semantizer
vla5924-practice/compiler-project pull request #44
Opened 2022-03-31 14:53 UTC by arteboss

2022-04-07 16:05 UTC, vla5924 commented
@arteboss #24 замержили, можно тестировать

2022-04-13 10:32 UTC, vla5924 commented
Нужно еще сделать тесты на то что выкидываются ошибки при наличии необъявленных переменных и т.д. и проверку на то что есть `main` функция

2022-04-13 10:32 UTC, vla5924 commented
Нужно еще сделать тесты на то что выкидываются ошибки при наличии необъявленных переменных и т.д. и проверку на то что есть `main` функция

2022-04-14 10:04 UTC, MaksimShagov commented on backend/src/semantizer/semantizer.cpp
> +        errors.push<SemantizerError>(Node(), "Undefined reference to main");
Может быть стоит сразу возвращается из функции, когда нет mainа? @vla5924, что скажешь?

2022-04-14 10:06 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +        errors.push<SemantizerError>(Node(), "Undefined reference to main");
Может и стоит

2022-04-14 10:25 UTC, vla5924 requested changes
Предложения изменений можно принять хором на вкладке Files changed -> Add suggestion to batch для каждого -> Commit

2022-04-14 10:25 UTC, vla5924 commented on ast/src/node.cpp
> +    }
фигурные скобки лишние

2022-04-14 10:25 UTC, vla5924 commented on ast/src/node.cpp
> +        }
`BranchRoot` и `\n` выводятся в поток безусловно, они должны быть вне if

2022-04-14 10:25 UTC, vla5924 commented on ast/src/node.cpp
>          }
Аналогично, `Expression` и `\n`

2022-04-14 10:25 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +    }
Это что за велосипед? Метод find для вас какая-то шутка?

2022-04-14 10:25 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +        errors.push<SemantizerError>(Node(), "Undefined reference to main");
Вообще-то, пожалуй, стоит добавить конструктор для SemantizerError только со строкой. Разумеется, explicit.
А еще `Undefined reference to main` это как по мне неподходящая строка в нашем случае. В случае С++ компоновщик сам вставляет вызов main, соответственно падает при отсутствии этой функции и отсюда такое сообщение. А мы ничего не вставляем, мы просто требуем чтобы она была. Поэтому можно здесь использовать например `Function 'main' is not declared, although it has to be`

2022-04-14 10:25 UTC, vla5924 commented on tests/backend/semantizer.cpp
> +TEST(Semantizer, can_insert_type_conversion_float_constant_to_int) {
```suggestion
TEST(Semantizer, can_insert_type_conversion_float_literal_to_int) {
```

2022-04-14 10:25 UTC, vla5924 commented on tests/backend/semantizer.cpp
> +TEST(Semantizer, can_insert_type_conversion_int_constant_to_float) {
```suggestion
TEST(Semantizer, can_insert_type_conversion_int_literal_to_float) {
```

2022-04-14 10:25 UTC, vla5924 commented on tests/backend/semantizer.cpp
> +TEST(Semantizer, dont_insert_type_conversion_int_int) {
```suggestion
TEST(Semantizer, does_not_insert_type_conversion_for_ints) {
```

2022-04-14 10:25 UTC, vla5924 commented on tests/backend/semantizer.cpp
> +TEST(Semantizer, dont_insert_type_conversion_float_float) {
```suggestion
TEST(Semantizer, does_not_insert_type_conversion_for_floats) {
```

2022-04-14 10:25 UTC, vla5924 commented on tests/backend/semantizer.cpp
> +TEST(Semantizer, dont_raise_error_on_redeclaration_of_variable_in_different_scopes) {
```suggestion
TEST(Semantizer, can_declare_variables_with_same_names_in_different_scopes) {
```

2022-04-14 10:25 UTC, vla5924 commented on tests/backend/semantizer.cpp
> +    ASSERT_ANY_THROW(Semantizer::process(tree));
Здесь и ниже - достоверно известно, объект какого класса должен выкинуться. Нужно это указать в `ASSERT_THROW`

2022-04-14 10:25 UTC, vla5924 commented on ast/src/node.cpp
> +void variablesTableToString(std::ostream &stream, const VariablesTable &table) {
Тогда уж `dumpVariablesTable`

2022-04-14 10:32 UTC, MaksimShagov commented on backend/src/semantizer/semantizer.cpp
> +    }
![image](https://user-images.githubusercontent.com/43129418/163370819-ec4ea248-70be-4a18-bdc2-df4824525391.png)

2022-04-14 10:51 UTC, vla5924 requested changes

2022-04-14 10:51 UTC, vla5924 commented on ast/src/node.cpp
> +            stream << ":";
```suggestion
            stream << ':';
```

2022-04-14 10:51 UTC, vla5924 commented on ast/src/node.cpp
> +        stream << "\n";
```suggestion
        stream << '\n';
```

2022-04-14 10:51 UTC, vla5924 commented on ast/src/node.cpp
> +        stream << "\n";
```suggestion
        stream << '\n';
```

2022-04-14 10:53 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +        errors.push<SemantizerError>(Node(), "Undefined reference to main");
Вообще-то зачем, это ведь не мешает нам сделать обход дерева и проверить наличие других ошибок. Для пользователя так будет удобнее

2022-04-14 10:55 UTC, vla5924 requested changes

2022-04-14 10:55 UTC, vla5924 commented on tests/backend/semantizer.cpp
> +TEST(Semantizer, raise_error_on_undefined_reference_to_main) {
```suggestion
TEST(Semantizer, raise_error_on_undefined_main_function) {
```

2022-04-14 10:57 UTC, vla5924 approved these changes
![](https://user-images.githubusercontent.com/43135873/163377843-914d8336-4e94-44bd-895f-dd15785db7ca.jpg)

2022-04-14 10:57 UTC, MaksimShagov commented on backend/src/semantizer/semantizer.cpp
> +        errors.push<SemantizerError>(Node(), "Undefined reference to main");
Да, я поэтому и спросил

2022-04-14 10:58 UTC, MaksimShagov approved these changes

2022-04-14 10:58 UTC, merged