Implemented SemantizerContext
vla5924-practice/compiler-project pull request #73
Opened 2022-05-23 09:16 UTC by MaksimShagov

2022-05-23 09:56 UTC, vla5924 requested changes

2022-05-23 09:56 UTC, vla5924 commented on backend/include/backend/semantizer/semantizer_context.hpp
> +#include "semantizer_error.hpp"
![15197395](https://user-images.githubusercontent.com/43135873/169792730-adfa66dd-0040-43a2-84a9-1f0945c5279b.jpg)

```suggestion
#include "semantizer_error.hpp"

```

2022-05-23 09:56 UTC, vla5924 commented on backend/include/backend/semantizer/semantizer_context.hpp
> +    std::list<ast::VariablesTable *> tables;
Лучше `variables` (по аналогии с `functions`)

2022-05-23 09:56 UTC, vla5924 commented on backend/include/backend/semantizer/semantizer_context.hpp
> +    ast::TypeId searchVariable(const ast::Node::Ptr &node) {
Для функции больше подходит название `findVariable`

2022-05-23 09:56 UTC, vla5924 commented on backend/include/backend/semantizer/semantizer_context.hpp
> +            ast::VariablesTable::const_iterator table_name = table->find(node->str());
1. `auto` вместо полного имени типа 🙂
2. `node->str()` на каждой итерации вызывается, идея для переменной `const std::string &` 🙂🙂
3. camelCase передает привет 🙂🙂🙂

2022-05-23 09:56 UTC, vla5924 commented on backend/src/semantizer/semantizer.cpp
> +            VariablesTable::const_iterator table_name = ctx.tables.front()->find(name);
```suggestion
            auto table_name = ctx.tables.front()->find(name);
```

2022-05-23 10:16 UTC, MaksimShagov commented on backend/include/backend/semantizer/semantizer_context.hpp
> +            ast::VariablesTable::const_iterator table_name = table->find(node->str());
![image](https://user-images.githubusercontent.com/43129418/169798073-ccde721f-9ee3-4cee-9e36-44d5c33e998f.png)

2022-05-25 13:13 UTC, vla5924 approved these changes
![ZHpkyfc9CilJALXnL2GRWRFjguCvhckIoA5Dux1qqFQKvxa4k1afVICroVYgqalKVQWfS_R0XcA3PbQ7kfHwW1hk](https://user-images.githubusercontent.com/43135873/170270225-83f08ccb-2012-4477-97a5-25fd403ec456.jpg)

2022-05-25 13:17 UTC, merged