Implemented DCE Unused Variables
vla5924-practice/compiler-project pull request #88
Opened 2022-05-31 14:11 UTC by arteboss

2022-06-03 14:53 UTC, vla5924 approved these changes

2022-06-03 15:48 UTC, MaksimShagov requested changes

2022-06-03 15:48 UTC, MaksimShagov commented on backend/src/optimizer/optimizer.cpp
> +                // ctx.variables.front()->erase(name);
думаю это уже не нужно

2022-06-03 18:03 UTC, vla5924 commented on backend/src/optimizer/optimizer.cpp
> +                // ctx.variables.front()->erase(name);
ok

2022-06-03 18:03 UTC, vla5924 approved these changes

2022-06-06 09:40 UTC, MaksimShagov approved these changes

2022-06-06 09:40 UTC, merged